name: Build Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check if Base Image Updated
        id: image_update_check
        if: github.event_name == 'schedule'
        uses: lucacome/docker-image-update-checker@v2.0.0
        with:
          base-image: "node:alpine"
          image: "${{ secrets.DOCKER_USERNAME }}/ollama-model-proxy:latest"

      - name: Set up QEMU
        if: github.event_name == 'push' || steps.image_update_check.outputs.needs-updating == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: github.event_name == 'push' || steps.image_update_check.outputs.needs-updating == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name == 'push' || steps.image_update_check.outputs.needs-updating == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        if: github.event_name == 'push' || steps.image_update_check.outputs.needs-updating == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ollama-model-proxy:latest
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/s390x
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/ollama-model-proxy:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/ollama-model-proxy:buildcache,mode=max
