name: Build Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Check if update needed
        id: check
        run: |
          if [[ "${{ github.event_name }}" != "schedule" ]]; then
            echo "should_build=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          manifest=$(docker manifest inspect node:alpine)
          base_digest=$(echo "$manifest" | jq -r '.manifests[0].digest // ""')
          
          our_manifest=$(docker manifest inspect ${{ secrets.DOCKER_USERNAME }}/ollama-model-proxy:latest 2>/dev/null || echo '{"manifests":[]}')
          our_digest=$(echo "$our_manifest" | jq -r '.manifests[0].digest // ""')
          
          if [[ "$base_digest" != "$our_digest" ]]; then
            echo "should_build=true" >> $GITHUB_OUTPUT
          else
            echo "should_build=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: detect
    if: needs.detect.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ollama-model-proxy:latest
          platforms: linux/amd64,linux/arm64
